### ISSUE TITLE
Do a 'git pull' when merge a feature into release

### ISSUE THREAD

**Issue by kdivan** [monsieurchico/php-twgit#44]
Check clean working tree...
#git git fetch origin --prune
Check remote release...
Check remote feature...
#shell twgit feature start CAC-1276
#shell git pull origin feature/CAC-1276
#shell twgit release start --silent
#shell git merge --no-ff feature/CAC-1276
#shell git push origin release/10.40.0
ERROR : To bitbucket.org:prismamediadigital/cac.git
 ! [rejected]        release/10.40.0 -> release/10.40.0 (non-fast-forward)
error: failed to push some refs to 'git@bitbucket.org:prismamediadigital/cac.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
Merge branch 'release/10.40.0' of bitbucket.org:prismamediadigital/cac into release/10.40.0
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

When doing a twgit feature merge-into-release, it does a 'git fetch' and it's not followed by a 'git merge'; or replace it by a 'git pull' ?

**Comment by monsieurchico** [comment]
done
