### ISSUE TITLE
Check update but not execute command

### ISSUE THREAD

**Issue by kdivan** [monsieurchico/php-twgit#46]
➜  fem-bundle git:(release/7.21.0) twgit release finish
Your application has not been updated since 2017-03-02 16:36:11
(i) Current revision is "0.16.5" and remote revision "0.16.5".
➜  fem-bundle git:(release/7.21.0) twgit release finish

When I do a twgit command, it checks the last update done but does not execute the passed command. I have to execute twice.

**Comment by monsieurchico** [comment]
done.
